---
title: "Exploratory Biomarker Analyses, BRAIN-ICU Study"
author: 'Jennifer Thompson, MPH; Supervisor: Rameela Chandrasekhar, PhD'
date: "September 9, 2015"
output: html_document
---

```{r setup}
if(Sys.info()['sysname'] == 'Darwin'){
  load('/Volumes/thomps23/ICUDelirium/BRAINICU/braindata.Rdata')
} else{
  load('/home/thomps23/ICUDelirium/BRAINICU/braindata.Rdata')
}

biomarker.list <- c('crp', 'ifngamma', 'il10', 'il12', 'il1b', 'il6', 'il8', 'mmp9', 'proteinc', 'tnfa', 'tnfr1')

library(dplyr)
library(tidyr)
library(Hmisc)
library(caTools)

## -- Function to round and format numeric value to same number of places -- ##
round.format <- function(quant, dig = 0){
  format(round(quant, digits = dig), nsmall = dig)
}

## -- Function to create string of descriptive statistics for plots -- ##
get.results.string <- function(qn, q50, q25, q75, qmean, qsd){
  gsub(' +', ' ',
       paste0('N: ', qn, ' (', round((qn / nrow(brain.oneobs))*100),
         '%)\nMedian (IQR): ', round.format(q50, dig = 2),
           ' (', round.format(q25, dig = 2), ', ', round.format(q75, dig = 2),
         ')\nMean (SD): ', round.format(qmean, dig = 2), ' (', round.format(qsd, dig = 3), ')'))
}

# Multiple plot function: Winston Chang, R Cookbook
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  library(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}
```

We present descriptive statistics and data visualizations for the `r length(biomarker.list)`
biomarkers collected in both the BRAIN-ICU and MIND-ICU cohorts. For speed and ease, only BRAIN-ICU
data is included here, assuming that patterns will be similar for MIND-ICU.

```{r descstats}
## -- Calculate mean, peak, minimum, change, and AUC of each biomarker for each patient -- ##
bio.summary.pt <- brain.daily[,c('id', 'study.day', paste0(biomarker.list, '.imp'))] %>%
  gather(key = bio.marker, value = bio.value, crp.imp:tnfr1.imp) %>%
  filter(!is.na(bio.value)) %>%
  arrange(id, study.day) %>%
  group_by(id, bio.marker) %>%
  summarise(pt.n = sum(!is.na(bio.value)),
            pt.mean = mean(bio.value, na.rm = TRUE),
            pt.min = min(bio.value, na.rm = TRUE),
            pt.max = max(bio.value, na.rm = TRUE),
            pt.first = head(bio.value, n = 1),
            pt.last = tail(bio.value, n = 1),
            pt.auc = trapz(x = study.day, y = bio.value))
bio.summary.pt$pt.delta <- with(bio.summary.pt, ifelse(pt.n == 1, NA, pt.last - pt.first))

## -- Summary statistics for each biomarker across all patients; create strings to put on plots -- ##
## Spaghetti plots: % (number) of patients with 1, 2, 3 biomarker measurements
## Min, max, mean, delta, AUC: N, median (IQR), mean (SD)
bio.summary <- bio.summary.pt %>%
  group_by(bio.marker) %>%
  summarise(n.1 = sum(pt.n == 1, na.rm = TRUE),
            n.2 = sum(pt.n == 2, na.rm = TRUE),
            n.3 = sum(pt.n == 3, na.rm = TRUE),
            mean.n = sum(!is.na(pt.mean)),
            mean.25 = quantile(pt.mean, probs = 0.25, na.rm = TRUE),
            mean.50 = quantile(pt.mean, probs = 0.50, na.rm = TRUE),
            mean.75 = quantile(pt.mean, probs = 0.75, na.rm = TRUE),
            mean.mean = mean(pt.mean, na.rm = TRUE),
            mean.sd = sd(pt.mean, na.rm = TRUE),
            min.n = sum(!is.na(pt.min)),
            min.25 = quantile(pt.min, probs = 0.25, na.rm = TRUE),
            min.50 = quantile(pt.min, probs = 0.50, na.rm = TRUE),
            min.75 = quantile(pt.min, probs = 0.75, na.rm = TRUE),
            min.mean = mean(pt.min, na.rm = TRUE),
            min.sd = sd(pt.min, na.rm = TRUE),
            max.n = sum(!is.na(pt.max)),
            max.25 = quantile(pt.max, probs = 0.25, na.rm = TRUE),
            max.50 = quantile(pt.max, probs = 0.50, na.rm = TRUE),
            max.75 = quantile(pt.max, probs = 0.75, na.rm = TRUE),
            max.mean = mean(pt.max, na.rm = TRUE),
            max.sd = sd(pt.max, na.rm = TRUE),
            delta.n = sum(!is.na(pt.delta)),
            delta.25 = quantile(pt.delta, probs = 0.25, na.rm = TRUE),
            delta.50 = quantile(pt.delta, probs = 0.50, na.rm = TRUE),
            delta.75 = quantile(pt.delta, probs = 0.75, na.rm = TRUE),
            delta.mean = mean(pt.delta, na.rm = TRUE),
            delta.sd = sd(pt.delta, na.rm = TRUE),
            auc.n = sum(!is.na(pt.auc)),
            auc.25 = quantile(pt.auc, probs = 0.25, na.rm = TRUE),
            auc.50 = quantile(pt.auc, probs = 0.50, na.rm = TRUE),
            auc.75 = quantile(pt.auc, probs = 0.75, na.rm = TRUE),
            auc.mean = mean(pt.auc, na.rm = TRUE),
            auc.sd = sd(pt.auc, na.rm = TRUE)) %>%
  mutate(n.pct = paste0('Measurements / Pt:\n1: ',
                        round((n.1 / nrow(brain.oneobs))*100), '% (', n.1,
                        ')\n2: ', round((n.2 / nrow(brain.oneobs))*100), '% (', n.2,
                        ')\n3: ', round((n.3 / nrow(brain.oneobs))*100), '% (', n.3, ')'),
         mean.desc = get.results.string(mean.n, mean.50, mean.25, mean.75, mean.mean, mean.sd),
         min.desc = get.results.string(min.n, min.50, min.25, min.75, min.mean, min.sd),
         max.desc = get.results.string(max.n, max.50, max.25, max.75, max.mean, max.sd),
         delta.desc = get.results.string(delta.n, delta.50, delta.25, delta.75, delta.mean, delta.sd),
         auc.desc = get.results.string(auc.n, auc.50, auc.25, auc.75, auc.mean, auc.sd))

## Set text sizes
histspag.axis.text <- 7
summaryhist.axis.title <- 8
summaryhist.axis.text <- 6

## -- Function to create histograms of summary statistics -- ##
bio.hist <- function(usedata,   ## data set to use
                     xvar,      ## character string - name of variable on X axis
                     xlabel,    ## character string - label for X axis
                     resultstr, ## character string - descriptive statistics
                     resultx){  ## numeric - x value for placement of correlation results
  ## Replace name of biomarker with "xvar" to allow use in ggplot
  names(usedata) <- gsub(xvar, 'xvar', names(usedata))
  
  ggplot(aes(x = xvar), data = usedata) +
    geom_histogram(fill = 'blue', alpha = 0.3) +
    scale_x_continuous(name = xlabel) +
    scale_y_continuous(name = 'Frequency') +
    ## Add descriptive statistics
    annotate(geom = 'text', label = as.character(resultstr),
             x = resultx, y = Inf, vjust = 1.5, hjust = 1, size = 2.5) +
    theme_minimal() +
    theme(axis.title = element_text(size = summaryhist.axis.title),
          axis.text = element_text(size = summaryhist.axis.text))
}

## -- Function to create all plots for a given biomarker -- ##
bio.plots <- function(use.bio){
  ## Select only data needed for plots: id, study day, biomarker specified
  use.daily <- brain.daily[brain.daily$study.day %in% c(1, 3, 5), c('id', 'study.day', use.bio)]
  ## Replace actual biomarker name with generic "use.bio" to use in ggplot
  names(use.daily) <- gsub(use.bio, 'use.bio', names(use.daily))
  
  ## Get summary values, descriptive statistics for specified biomarker
  use.summary <- bio.summary.pt[bio.summary.pt$bio.marker == use.bio,]
  use.desc <- bio.summary[bio.summary$bio.marker == use.bio,]
  
  ## Create histogram of all biomarker values, regardless of study day
  bio.hist.all <- ggplot(aes(x = use.bio), data = use.daily) +
    geom_histogram(alpha = 0.3, fill = 'blue') +
    scale_x_continuous(name = 'Biomarker Value, All Study Days') +
    scale_y_continuous(name = 'Frequency') +
    ## Add number of measurements per patient
    annotate(geom = 'text', label = use.desc$n.pct,
             x = max(use.daily$use.bio, na.rm = TRUE), y = Inf,
             vjust = 1.3, hjust = 1, size = 2.5) +
    ## Add title - biomarker name
    ggtitle(toupper(gsub('\\.imp$', '', use.bio))) +
    theme_minimal() +
    theme(title = element_text(hjust = 0, size = 18, face = 'bold'),
          axis.title = element_text(hjust = 0.5, vjust = 0.5, face = 'plain', size = 10),
          axis.text = element_text(size = histspag.axis.text))
  
  ## Create spaghetti plot of biomarker value by study day per patient
  bio.spaghetti <- ggplot(aes(x = study.day, y = use.bio, group = id), data = use.daily) +
    geom_line(alpha = 0.15, colour = 'blue') +
    scale_x_continuous(breaks = c(1, 3, 5), name = 'Study Day') +
    scale_y_continuous(name = 'Biomarker Value') +
    theme_minimal() +
    theme(axis.text = element_text(size = histspag.axis.text))
  
  ## Create histograms of summary values (mean, min, max, delta, AUC)
  bio.mean.hist <- bio.hist(usedata = use.summary,
                            'pt.mean', 'Patient Mean',
                            use.desc$mean.desc, max(use.summary$pt.mean, na.rm = TRUE))
  bio.min.hist <- bio.hist(usedata = use.summary,
                           'pt.min', 'Patient Minimum',
                           use.desc$min.desc, max(use.summary$pt.min, na.rm = TRUE))
  bio.max.hist <- bio.hist(usedata = use.summary,
                           'pt.max', 'Patient Maximum',
                           use.desc$max.desc, max(use.summary$pt.max, na.rm = TRUE))
  bio.delta.hist <- bio.hist(usedata = use.summary,
                             'pt.delta', 'Patient Change, Last - First',
                             use.desc$delta.desc, max(use.summary$pt.delta, na.rm = TRUE))
  bio.auc.hist <- bio.hist(usedata = use.summary,
                           'pt.auc', 'Patient AUC',
                           use.desc$auc.desc, max(use.summary$pt.auc, na.rm = TRUE))
  
  return(list('total.hist' = bio.hist.all,
              'spaghetti' = bio.spaghetti,
              'mean.hist' = bio.mean.hist,
              'min.hist' = bio.min.hist,
              'max.hist' = bio.max.hist,
              'delta.hist' = bio.delta.hist,
              'auc.hist' = bio.auc.hist))
}

## Create list with one element per biomarker, each element has all plots for that marker
all.bio.plots <- lapply(paste0(biomarker.list, '.imp'), bio.plots)

## -- Function to plot all six plots per biomarker using multiplot() -- ##
multiplot.bio <- function(bio.plot.list){
  multiplot(bio.plot.list$total.hist, bio.plot.list$spaghetti,
            bio.plot.list$mean.hist, bio.plot.list$min.hist, bio.plot.list$max.hist,
            bio.plot.list$delta.hist, bio.plot.list$auc.hist,
            layout = matrix(c(1, 2, 6, 1, 2, 7, 3, 4, 5), ncol = 3))
}

pdf(file = 'biomarker_descplots.pdf', width = 10.5, height = 8, onefile = TRUE)
for(i in 1:length(all.bio.plots)){
  multiplot.bio(all.bio.plots[[i]])
}
dev.off()

```


```{r, echo=FALSE}
## -- Scatterplots and correlation statistics for day 1 values -- ##
## Get all day 1 values into a matrix
day1.data <- subset(brain.daily, study.day == 1)[,c(paste0(biomarker.list, '.imp'))]

## -- Get data frame with all unique combinations of biomarkers -- ##
## Use expand.grid to get all unique combinations, but includes duplicates
marker.combs <- expand.grid(names(day1.data), names(day1.data))

## Create new variable that is *sorted* marker1_marker2
marker.combs$unique.comb <- unlist(lapply(1:nrow(marker.combs), FUN = function(i){
  markervals <- c(as.character(marker.combs[i, 'Var1']), as.character(marker.combs[i, 'Var2']))
  paste(sort(markervals), collapse = '_') }))

## Use strsplit to get all sorted combinations of biomarkers, then take all unique values
markercomb.strsplit <- lapply(unique(marker.combs$unique.comb), FUN = strsplit, split = '_')
marker.comb.unique <-
  data.frame(marker1 = unlist(lapply(markercomb.strsplit, FUN = function(x){ x[[1]][1] })),
             marker2 = unlist(lapply(markercomb.strsplit, FUN = function(x){ x[[1]][2] })))
marker.comb.unique <- subset(marker.comb.unique, marker1 != marker2)

## -- Create matrix for multiplot: lower triangle is scatterplots, upper triangle is rho/Ps -- ##
corrplotmat <- matrix(NA, ncol = length(biomarker.list), nrow = length(biomarker.list))
corrplotmat[lower.tri(corrplotmat)] <- 1:sum(lower.tri(corrplotmat))
corrplotmat <- t(corrplotmat)
corrplotmat[lower.tri(corrplotmat)] <- 1:sum(lower.tri(corrplotmat))
corrplotmat[upper.tri(corrplotmat)] <- corrplotmat[upper.tri(corrplotmat)] + sum(lower.tri(corrplotmat))
diag(corrplotmat) <- (sum(!is.na(corrplotmat)) + 1):length(corrplotmat)

## Function to create scatterplot with smoother, given an X and Y biomarker
scattersmooth <- function(xvar, yvar){
  if(xvar == yvar){
    return(NULL)
  } else{
    usedata <- day1.data[,c(xvar, yvar)]
    names(usedata) <- c('xvar', 'yvar')
    
    ggplot(aes(x = xvar, y = yvar), data = usedata) +
      geom_point(size = 1, alpha = 0.2) +
      geom_smooth(alpha = 0.2) +
      theme_minimal() +
      labs(x = NULL, y = NULL) +
      theme(axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.grid = element_blank(),
            plot.margin=unit(c(0,0,0,0),"mm"))
  }
}

all.scatter <- lapply(1:nrow(marker.comb.unique), FUN = function(i){
  scattersmooth(xvar = marker.comb.unique[i, 1], yvar = marker.comb.unique[i, 2])
})

## Function to create "plot" with rho, p-value, given an X and Y biomarker
rhop <- function(xvar, yvar){
  if(xvar == yvar){
    return(NULL)
  } else{
    usedata <- day1.data[,c(xvar, yvar)]
    names(usedata) <- c('xvar', 'yvar')
    
    corrstats <- rcorr(as.matrix(usedata[,1:2]), type = 'spearman')
    corrstr <- paste0('N: ', corrstats$n['xvar', 'yvar'],
                      '\nR: ', round.format(corrstats$r['xvar', 'yvar'], dig = 2),
                      '\nP: ', round.format(corrstats$P['xvar', 'yvar'], dig = 3))
    ggplot(aes(x = xvar, y = yvar), data = usedata) +
      annotate(geom = 'text', label = corrstr, size = 3,
               x = mean(usedata$xvar, na.rm = TRUE), y = mean(usedata$yvar, na.rm = TRUE)) +
      theme_minimal() +
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.grid = element_blank(),
            plot.margin=unit(c(0,0,0,0),"mm"))
  }
}

all.rho <- lapply(1:nrow(marker.comb.unique), FUN = function(i){
  rhop(xvar = marker.comb.unique[i, 1], yvar = marker.comb.unique[i, 2])
})

## Create "plots" with text for biomarker labels to put on diagonals
bio.plot.fakedata <- data.frame(xval = 1:10, yval = 1:10)
bio.plots <- lapply(biomarker.list, FUN = function(marker){
  ggplot(aes(x = xval, y = yval), data = bio.plot.fakedata) +
      annotate(geom = 'text', label = toupper(marker),
               x = 5.5, y = 5.5, face = 'bold', colour = 'navy', size = 3.7) +
      theme_minimal() +
      theme(axis.title = element_blank(),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            panel.grid = element_blank(),
            plot.margin=unit(c(0,0,0,0),"mm"))
})

## Create final PDF
pdf('scattercorr.pdf', width = 10.5, height = 8)
multiplot(plotlist = c(all.scatter, all.rho, bio.plots),
          layout = corrplotmat)
dev.off()

```

```{r varclus}
pdf(file = 'biomarker_varclus.pdf', width = 7, height = 6, onefile = TRUE)
plot(varclus(as.matrix(day1.data))) + title('Spearman rho')
plot(varclus(as.matrix(day1.data), similarity = 'hoeffding')) + title("Hoeffding's D")
dev.off()

```

```{r redundancy}
## Create data set to use for redundancy analyses
brain.daily.use <- brain.daily[brain.daily$study.day %in% c(1, 3, 5),
                               c('id', 'study.day', paste0(biomarker.list, '.imp'))]

## -- Function to print redun() results in ggplot form -- ##
redun.ggplot <- function(redun.obj){
  redun.rsq <- sort(redun.obj$rsq1, decreasing = FALSE)
  redun.data <- data.frame(var = names(redun.rsq),
                           rsq = as.numeric(redun.rsq),
                           index = 1:length(redun.rsq))
  redun.plot <- ggplot(aes(x = rsq, y = index), data = redun.data) +
                  geom_point() +
                  scale_x_continuous(limits = c(0, 1)) +
                  scale_y_continuous(limits = c(1, length(redun.rsq)),
                                     breaks = 1:length(redun.rsq),
                                     labels = redun.data$var) +
                  xlab(expression(R^2)) +
                  ylab('')
  return(redun.plot)
}

## -- Specify R2 cutoff -- ##
r2.min <- 0.6

## Redundancy analyses
allbio.redun <- redun(as.formula(paste('~ ', paste(paste0(biomarker.list, '.imp'), collapse = ' + '))),
                      data = brain.daily.use,
                      nk = 5,
                      r2 = r2.min)
allbio.redun.plot <- redun.ggplot(allbio.redun)

day1bio.redun <- redun(as.formula(paste('~ ', paste(paste0(biomarker.list, '.imp'), collapse = ' + '))),
                       data = subset(brain.daily.use, study.day == 1),
                       nk = 5,
                       r2 = r2.min)
day1bio.redun.plot <- redun.ggplot(day1bio.redun)

## Create plot with both versions on a single panel, sorted by "all days" R2
rsq.order <- data.frame(marker = names(allbio.redun$rsq1),
                        marker.order = order(allbio.redun$rsq1, decreasing = FALSE))

all.redun.rsq <- data.frame(marker = rep(names(sort(allbio.redun$rsq1)), 2))
all.redun.rsq$rsq.val <- c(allbio.redun$rsq1[all.redun.rsq$marker[1:length(allbio.redun$rsq1)]],
                           day1bio.redun$rsq1[all.redun.rsq$marker[1:length(day1bio.redun$rsq1)]])
all.redun.rsq$which.rsq <- factor(c(rep('All study days', length(names(allbio.redun$rsq1))),
                                    (rep('Day 1 only', length(names(allbio.redun$rsq1))))))
all.redun.rsq$plot.order <- rep(1:length(allbio.redun$rsq1), 2)

pdf(file = 'redundancy.pdf', width = 6, height = 6)
ggplot(aes(x = rsq.val, y = plot.order, colour = which.rsq), data = all.redun.rsq) +
  geom_point(size = 3, alpha = 0.7) +
  scale_colour_discrete(name = 'Days used') +
  scale_x_continuous(limits = 0:1, name = expression(R^2)) +
  scale_y_continuous(name = '',
                     breaks = unique(all.redun.rsq$plot.order),
                     labels = toupper(gsub('\\.imp$', '', all.redun.rsq$marker[1:length(allbio.redun$rsq1)]))) +
  theme_minimal() +
  theme(legend.position = c(1, 0), legend.justification = c(1, 0), axis.ticks = element_blank())
dev.off()

```